const levels = {
  thinkingspaceii: {
    name: "Thinking Space II",
    creator: "CairoX and more",
    verifier: "Zoink",
    id: "119544028",
    password: "Free Copy",
    length: "1m 9s",
    object: "139,568",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "CELNmHwln_c",
    bgColor: "#2b2330",
    song: "Nuke Powder by MaelouX (ID 489111)",
    description: "A mindscape of pure insanity, most fall to it's brutal nature. Gameplay by CoCy team, Deco hosted by DrCuber, Verified by Zoink. Dedicated to Hideki <3",
    trivia: "Current Top 1(1 hour(before Amethyst) + 49 days(cbf blocker placed on Amethyst) + now), Cbf blocker deleted"
  },
  amethyst: {
    name: "Amethyst",
    creator: "iMist and more",
    verifier: "wPopoff",
    id: "119550490",
    password: "Free Copy",
    length: "1m 42s",
    object: "147,177",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "4lfkzz1VCbA",
    bgColor: "#120e1a",
    song: "-Ricochet Love- by Waterflame (ID 233860)",
    description: "An idea that started 5 years ago has now been brought to light. Venture into the depths of the cave to fulfill an ancient legend. Will you be the one to find the Amethyst crystal?",
    trivia: "Former Top 1(248 days(because of cbf blocker)), Cbf blocker deleted"
  },
  flamewall: {
    name: "Flamewall",
    creator: "Narwall and more",
    verifier: "Cuatrocientos",
    id: "126242564",
    password: "Free Copy",
    length: "6m 46s",
    object: "413,736",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "Epic",
    youtube: "x4Io4zkWVRw",
    bgColor: "#3d2400",
    song: "Flamewall by Camellia (ID 10007151(library)",
    description: "The ultimate endurance test, in the works since 2022. | Verified by Cuatrocientos in 221.703k attempts.",
    trivia: "Cbf blocker deleted"
  },
  tidalwave: {
    name: "Tidal Wave",
    creator: "OniLink",
    verifier: "Zoink",
    id: "86407629",
    password: "Free Copy",
    length: "3m 0s",
    object: "220,115",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "-",
    youtube: "9fsZ014qB3s",
    bgColor: "#003a47",
    song: "Tidal Wave(Shiawase VIP rmx) by RunoNG (ID 1266014), Shiawave(VIP) by Dion Timmer (NONG)",
    description: "Drown them",
    trivia: "Former Top 1(162 days(Unrated) + 472 days(before Thinking Space II)"
  },
  oldorochi: {
    name: "Old Orochi",
    creator: "Platnuu",
    verifier: "SeptaGon7",
    id: "136742562",
    password: "Free Copy",
    length: "1m 34s",
    object: "71,821",
    version: "2.208",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "YxtFAQtLYQY",
    bgColor: "#6e0102",
    song: "Yomi yori Kikoyu Koukoku no Hi to Honoo no Shoujo by Monumia (ID 1389624), 黄泉より聴こゆ、皇国の燈と焔の少女。by Imperial Circus Dead Decadence (NONG)",
    description: "Verified by SeptaGon7",
    trivia: "Former impossible level, Current Top 1 of Unrated level"
  },
  orbit: {
    name: "ORBIT",
    creator: "MindCap and more",
    verifier: "Zoink",
    id: "133175713",
    password: "Free Copy",
    length: "3m 42s",
    object: "308,666",
    version: "2.208",
    difficulty: "Extreme Demon",
    rating: "Mythic",
    youtube: "QKcv8DkNPd0",
    bgColor: "#42022c",
    song: "Animation Warrior Theme by NightHawk22 (ID 80273)",
    description: "O",
    trivia: "First Mythic rated Extreme Demon"
  },
  saryneverclearog: {
    name: "SARY NEVER CLEAR",
    creator: "Optic Sunflow",
    verifier: "Glowgmd",
    id: "609629",
    password: "Copy Disabled",
    length: "1m 19s",
    object: "-",
    version: "1.6",
    difficulty: "Harder",
    rating: "Unrated",
    youtube: "Hpo77uVq75M",
    bgColor: "#054541",
    song: "Electroman Adventures by Waterflame (ingame song)",
    description: "GOOD LUCK",
    trivia: "Original version of SARY NEVER CLEAR, Former Top 1 of Unrated level"
  },
  nullscapes: {
    name: "Nullscapes",
    creator: "Kiba",
    verifier: "Zoink",
    id: "109780665",
    password: "Free Copy",
    length: "1m 21s",
    object: "63,179",
    version: "2.206",
    difficulty: "Extreme Demon",
    rating: "Mythic",
    youtube: "EztneTPp5CU",
    bgColor: "#454545",
    song: "Creo - Flow by CreoMusic (ID 1132447), Creo - Slow Down by CreoMusic (ID 800646)(intro)",
    description: "GET OUT OF MY HEAD",
    trivia: "Cbf blocker deleted, Hardest one mode level(only robot)"
  },
  sakupencirclesunnerfed: {
    name: "Sakupen circles",
    creator: "Nick24",
    verifier: "ad3us",
    id: "10887708",
    password: "Copy Disabled",
    length: "50s",
    object: "-",
    version: "1.9",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "AdrmZsy52EY",
    bgColor: "#421c02",
    song: "Iron God: Sakupen Hell Yes RMX by mr-jazzman (ID 360804)",
    description: "Another nine circles level. Hardest nine circles level ever created?",
    trivia: "Original version of Sakupen Circles, former Top 1 of Unrated level"
  },
  quanteuseprocessing: {
    name: "Quanteuse processing",
    creator: "Renn241 and Blankb",
    verifier: "Zoink",
    id: "117692518",
    password: "Free Copy",
    length: "1m 42s",
    object: "44,883",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "-",
    youtube: "j5NC0u1Q91Q",
    bgColor: "#4d0039",
    song: "Dash by MDK (ingame song), Blast Processing by Waterflame (ingame song)",
    description: "verified by zoink, level by blankb and I",
    trivia: "-"
  },
  penumbral: {
    name: "Penumbral",
    creator: "cherryteam",
    verifier: "w3rty",
    id: "134942736",
    password: "Free Copy",
    length: "1m 24s",
    object: "87,891",
    version: "2.208",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "nVHPFf13M-I",
    bgColor: "#592500",
    song: "xStep by DJVI (ingame song)",
    description: "Hosted by nxhtrise // Verified by w3rty.",
    trivia: "-"
  },
  boobawamba: {
    name: "BOOBAWAMBA",
    creator: "Akunakunn and more",
    verifier: "Eastshark",
    id: "110816181",
    password: "Free Copy",
    length: "2m 26s",
    object: "92,556",
    version: "2.206",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "20fYiqLAo_E",
    bgColor: "#253522",
    song: "Portal To The Other Side (feat. Hatsune Miku) by nandinanubis (ID 941913)",
    description: "BOOBAWAMBA is equal to {10, 100 [1[1\1\12-2] 1 [2\2-2]2]2} using the array of operator and BEAF it has boobol entries. This is my best level and it has been verified by EastShark",
    trivia: "Hardest memory level"
  },
  everyend: {
    name: "Every End",
    creator: "MindCap and more",
    verifier: "Hqmy",
    id: "116174063",
    password: "Free Copy",
    length: "7m 20s",
    object: "326,380",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "-",
    youtube: "AO--mVVFtKI",
    bgColor: "#253f5b",
    song: "Every End... by Dimrain47 (ID 99477)",
    description: "Never Ending",
    trivia: "-"
  },
  andromeda: {
    name: "andromeda",
    creator: "Insxne97",
    verifier: "Taiago",
    id: "114283297",
    password: "Free Copy",
    length: "1m 16s",
    object: "179,343",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "-",
    youtube: "mk3TDemdkC0",
    bgColor: "#220242",
    song: "omnipresent (AIM 2023) by WakerLink (ID 1216127), SR20DET by BIksmiith (NONG)",
    description: "verified by Taiago // playtested by guillexprex52, kywy, fusion425, swiborg, & others // ty to Xanify, Nemo, Grid, Triplash, Blayne, and more!",
    trivia: "-"
  },
  subsumingvortex: {
    name: "Subsuming Vortex",
    creator: "Cursed and more",
    verifier: "Cursed",
    id: "127997391",
    password: "Free Copy",
    length: "1m",
    object: "71,134",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "0eYG1ogJpIQ",
    bgColor: "#024231",
    song: "NK - Sine Wavs by Rukkus (ID 512976)",
    description: "The hardest nine circles level... at the time // By SeptaGon7 and Renn241",
    trivia: "Old impossible level(Unnerfed)"
  },
  vscx2: {
    name: "VSC x2",
    creator: "Nev9(BoBoBoBoBoBoBo)",
    verifier: "Nev9",
    id: "125131485",
    password: "Free Copy",
    length: "41s",
    object: "14,667",
    version: "2.207",
    difficulty: "Insane(Challenge)",
    rating: "Unrated",
    youtube: "92Msl_EI-5E",
    bgColor: "#423b02",
    song: "-Stalker- by Waterflame (ID 620959)",
    description: "173 completions, 1247822 attempts! verified by me",
    trivia: "A double VSC"
  },
  anathema: {
    name: "Anathema",
    creator: "Nikroplays and more",
    verifier: "Whizkid05",
    id: "112313819",
    password: "Free Copy",
    length: "2m 30s",
    object: "287,442",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "Epic",
    youtube: "_uKwmjHmySI",
    bgColor: "#42022c",
    song: "I Cant Fix You feat. Crusher-P by TheLivingTombstone (ID 717444)",
    description: "After 9 long years, The Dedication Series finally comes to a close. Dedicated to everyone who has supported me along the way. Verified by Whizkid05.",
    trivia: "-"
  },
  avernus: {
    name: "Avernus",
    creator: "PockeWindFish and more",
    verifier: "Zoink",
    id: "89496627",
    password: "30607",
    length: "1m 18s",
    object: "163,918",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "-",
    youtube: "16Zh8jssanc",
    bgColor: "#421802",
    song: "F-777 Dark Dragon Fire by F-777 (ID 91656)",
    description: "By Bo & Kyhros - https://discord.gg/YcNkfHMJGv",
    trivia: "Former Top 1"
  },
  aquamarine: {
    name: "Aquamarine",
    creator: "sincos and more",
    verifier: "seels",
    id: "77331805",
    password: "Free Copy",
    length: "1m 1s",
    object: "68,070",
    version: "2.206",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "Q__EnRojGt4",
    bgColor: "#020242",
    song: "cYsmix - Eden by cysmix (ID 718319)",
    description: "Originally made by me, redecorated by Renn241, with help from Cursed, Scorpion, and Taika. Very very special thanks to Flora4821. Enjoy the underwater trial :)",
    trivia: "The decoration was updated on August 2025"
  },
  ashleywavetrials: {
    name: "Ashley Wave Trials",
    creator: "OddMod",
    verifier: "Zoink",
    id: "62912799",
    password: "Free Copy",
    length: "2m 6s",
    object: "48,670",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "aTxt76U3e2Q",
    bgColor: "#971538",
    song: "Dr. Finkelfrackens Cure by bossfightofficial (ID 383158)",
    description: "My first time decorating like this!! ^^ Verified by Zoink",
    trivia: "Originally unnerfed, later modified by the creator"
  },
  silentclubstep: {
    name: "Silent clubstep",
    creator: "TheRealSailent",
    verifier: "zoe",
    id: "4125776",
    password: "Copy Disabled",
    length: "1m 27s",
    object: "10,906",
    version: "1.9",
    difficulty: "Extreme Demon",
    rating: "-",
    youtube: "GR4OMkS3SN8",
    bgColor: "#020024",
    song: "dj-nate - Clubstep (ingame song)",
    description: "7 years and you still play me?!",
    trivia: "Lost Top 1(underrated)"
  },
  thebloop: {
    name: "The Bloop",
    creator: "murkkat and more",
    verifier: "Zoink",
    id: "135661111",
    password: "Free Copy",
    length: "1m 46s",
    object: "108,897",
    version: "2.208",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "ROuXHSKEhHA",
    bgColor: "#191970",
    song: "larrynachos - We Are All Fucked (ID 890355)",
    description: "\"Beware the path this monster takes\" - Ozlip // All assets used with permission // Inspired by Kenos, verified by Zoink.",
    trivia: "-"
  },
  spectre: {
    name: "Spectre",
    creator: "xander556 and more",
    verifier: "PersonHuman42",
    id: "110815379",
    password: "Free Copy",
    length: "2m 44s",
    object: "298,848",
    version: "2.206",
    difficulty: "Extreme Demon",
    rating: "Epic",
    youtube: "MzsSLKJrLSI",
    bgColor: "#b545ff",
    song: "Creo - In Circles by CreoMusic (ID 786863)",
    description: "Extreme Demon Megacollab made by 40 amazing creators! Hosted by me. Verified by PersonHuman42 in 106,017 attempts.",
    trivia: "-"
  },
  acheron: {
    name: "Acheron",
    creator: "ryamu and more",
    verifier: "Zoink",
    id: "73667628",
    password: "Free Copy",
    length: "1m 6s",
    object: "47,965",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "sBKR6aUorzA",
    bgColor: "#1b0304",
    song: "{dj-N} Thermodynamix by dj-Nate (ID 770520)",
    description: "verified by zoink. \"get ricch or die trying\" -50 cent",
    trivia: "Former Top 1"
  },
  menace: {
    name: "Menace",
    creator: "Arraegen",
    verifier: "Whizkid05",
    id: "107805281",
    password: "Free Copy",
    length: "3m 4s",
    object: "77,620",
    version: "2.206",
    difficulty: "Extreme Demon",
    rating: "Epic",
    youtube: "nnkgghxxsEE",
    bgColor: "#825c03",
    song: "Menace by TheRealMannyHeffley (ID 1304920)",
    description: "\"The only truth in this world is that there is no truth.\" Verified by Whizkid. Level and song by me.",
    trivia: "Solo level(Song, Layout, Design)"
  },
  abyssofdarkness: {
    name: "Abyss of Darkness",
    creator: "Exen and more",
    verifier: "Cursed",
    id: "49896559",
    password: "030422",
    length: "2m 5s",
    object: "113,276",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "-",
    youtube: "ejJkpqcMMCY",
    bgColor: "#3d0d0d",
    song: "Death Note Dubstep [SB] by ShadowBeatzInc (ID 513539)",
    description: "-",
    trivia: "Former Top 1"
  },
  defeatedcircles: {
    name: "Defeated Circles",
    creator: "GXQ and more",
    verifier: "Zoink",
    id: "120012581",
    password: "Free Copy",
    length: "1m 5s",
    object: "84,298",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "-",
    youtube: "nU5AQPzd2YA",
    bgColor: "#60606e",
    song: "It Passed You By by SlendStone (ID 1234816), When You Find Me (Bonus Track) by plenka (NONG)",
    description: "Defeated. (Verified by Zoink)",
    trivia: "Remake version of old impossible level"
  },
  subterminalpoint: {
    name: "Subterminal Point",
    creator: "SyQual",
    verifier: "PoCle",
    id: "113599729",
    password: "Free Copy",
    length: "1m 10s",
    object: "40,970",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "h2wmRMgACH4",
    bgColor: "#00465d",
    song: "re:カレント by Miyolophone (ID 783614)",
    description: "Also inspired by Maplestory. Verified by PoCle",
    trivia: "-"
  },
  tunnelofdespair: {
    name: "Tunnel of Despair",
    creator: "Exen and ImMaxX1",
    verifier: "Zoink",
    id: "91351939",
    password: "Free Copy",
    length: "1m 44s",
    object: "75,309",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "LpS4JREhW98",
    bgColor: "#2c0000",
    song: "Silent Hill (Dubstep) by Jewelz123 (ID 386900)",
    description: "Tunnel of Despair. Gameplay by Exen, Deco by ImMaxX1, Verified by Zoink.",
    trivia: "-"
  },
  kyouki: {
    name: "Kyouki",
    creator: "Demishio",
    verifier: "Demishio",
    id: "86018142",
    password: "Free Copy",
    length: "1m 38s",
    object: "220,717",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "KDa5c0CJTHs",
    bgColor: "#39005e",
    song: "Creo - Crazy by CreoMusic (ID 905108)",
    description: "This is Crazy.",
    trivia: "Solo level(layout, design, verify)"
  },
  oldaod: {
    name: "Old AoD",
    creator: "Exen and more",
    verifier: "Dils thik",
    id: "76680844",
    password: "Free Copy",
    length: "2m 5s",
    object: "100,000",
    version: "2.11",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "RWBEfS4mLbw",
    bgColor: "#400501",
    song: "Death Note Dubstep [SB] by ShadowBeatzInc (ID 513539)",
    description: "-",
    trivia: "Old version of Abyss of Darkness"
  },
  swislithium: {
    name: "SWI Slithium",
    creator: "Hipo and more(Slithium)",
    verifier: "Hipo",
    id: "129774598",
    password: "Free Copy",
    length: "2m 3s",
    object: "45,311",
    version: "2.207",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "av5D0_M6hso",
    bgColor: "#002d80",
    song: "F-777 - Sonic Blaster by F-777 (ID 574484)",
    description: "Slithium's version of Sonic Wave Infinity, cancelled due to Xanii's verification. Verified by Hipo (me, not credited in the endscreen to stay faithful to the original copy).",
    trivia: "Buffed version(old impossible) of Sonic Wave Infinity"
  },
  re: {
    name: "Re",
    creator: "torn49",
    verifier: "torn49",
    id: "126279500",
    password: "Free Copy",
    length: "14s",
    object: "12,320",
    version: "2.207",
    difficulty: "Insane(Challenge)",
    rating: "Unrated",
    youtube: "Rz7Um6lxYYU",
    bgColor: "#252126",
    song: "- by - (ID 96), Innocent Days by Hitomi (NONG)",
    description: "\"I said that Geass was the power of the king which would condemn you to a life of solitude. I think maybe that's not quite correct. Right, Lelouch?\"",
    trivia: "Hardest challenge?"
  },
  illusionofhell: {
    name: "Illusion of Hell",
    creator: "Exen",
    verifier: "OverGD",
    id: "38230726",
    password: "Free Copy",
    length: "29s",
    object: "6,360",
    version: "2.11",
    difficulty: "Insane(Challenge)",
    rating: "Unrated",
    youtube: "nBmjrlmzUxE",
    bgColor: "#242222",
    song: "F-777 Dark Dragon Fire by F-777 (ID 96)",
    description: "-",
    trivia: "Former hardest challenge"
  },
  voltage: {
    name: "Voltage",
    creator: "ThePurgatory",
    verifier: "maybee",
    id: "131599104",
    password: "Free Copy",
    length: "1m 8s",
    object: "65,757",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "wBRvBN9tmlc",
    bgColor: "#593606",
    song: "{dj-N} Call the PoPo! by dj-Nate (ID 485224)",
    description: "Electricity, electrify, zaaap, electrons | Hosted by Phantom7Ks | Verified by Maybee | Gameplay by Lagnugg | 16-01-26 | #ThePurgatorySupremacy",
    trivia: "-"
  },
  thinkingspaceiiog: {
    name: "Thinking Space II",
    creator: "CoCyMain and more",
    verifier: "Zeronium",
    id: "132854166",
    password: "Free Copy",
    length: "1m 7s",
    object: "46,734",
    version: "2.208",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "RJedeB2wHCA",
    bgColor: "#404040",
    song: "Nuke Powder by MaelouX (ID 489111)",
    description: "Made to follow the original creators' project wishes. Original layout hosted by KugelBlitZ. Level hosted by Marcy and Sebi. Verified by Zeronium. Officially recognized by HidekiX",
    trivia: "Legacy version of Thinking Space II"
  },
  unnerfeddiabolicclubstep: {
    name: "Unnerfed Diabolic Cl",
    creator: "Sevant and IIIspitfireIII",
    verifier: "Sevant",
    id: "78149361",
    password: "Free Copy",
    length: "1m 27s",
    object: "20,006",
    version: "2.11",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "WHOfO0OxbvM",
    bgColor: "#400501",
    song: "Clubstep by DJ-Nate (ingame song)",
    description: "NOT the true unnerfed, which is lost. This is the closest version to it that I found, but probably not the hardest existing one.",
    trivia: "Unnerfed version of Diabolic Clubstep"
  },
  basedafterbased: {
    name: "Based After Based",
    creator: "Akunakunn and more",
    verifier: "DiamondSplash",
    id: "110534288",
    password: "Free Copy",
    length: "1m 28s",
    object: "99,072",
    version: "2.206",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "yQBFyUvB3lY",
    bgColor: "#630085",
    song: "Base After Base by DJVI (ID 404997)",
    description: "Welcome! This is a top 10 extreme demon with no spikes, no saws, no slopes, no waves, only duals and only 1x speed. Only verified by DiamondSplash aswell! Hope you all beat it too!",
    trivia: "Only dual & 1x speed, no spikes"
  },
  zorin: {
    name: "zorin",
    creator: "SnowEye(art by many people)",
    verifier: "9i",
    id: "134541844",
    password: "Free Copy",
    length: "2m 56s",
    object: "139,932",
    version: "2.208",
    difficulty: "Extreme Demon",
    rating: "Epic",
    youtube: "U19vmpenb9g",
    bgColor: "#944386",
    song: "Supernatural by zenkusaa (ID 1172938)",
    description: "Dedicated to my friends especially novi, ziglon Special thanks to Sonmok / Verified by 9i",
    trivia: "No spikes"
  },
  forgottenmaiden: {
    name: "Forgotten Maiden",
    creator: "ErinaLaSacarina",
    verifier: "sydno",
    id: "130217575",
    password: "Free Copy",
    length: "17s",
    object: "7,084",
    version: "2.207",
    difficulty: "Harder(Challenge)",
    rating: "Unrated",
    youtube: "iulSolHQcw0",
    bgColor: "#252126",
    song: "- by - (ID 42)",
    description: "The memories erased from a forgotten bunny... Verified by Sydno in 121.876 attempts. Dedicated to GemaYue and Frutos Secos.",
    trivia: "-"
  },
  iiishonpointercrate: {
    name: "3SH on Pointercrate",
    creator: "tahabht(UFokinWotM8)",
    verifier: "VovanPo",
    id: "127534241",
    password: "Free Copy",
    length: "20s",
    object: "7,134",
    version: "2.207",
    difficulty: "Insane(Challenge)",
    rating: "Unrated",
    youtube: "oY-rlZxhLUM",
    bgColor: "#42022c",
    song: "---Fury--- by Acid-Notation (ID 529291)",
    description: "\"omw to buy 3kg of bread at the 3shop joot\" verified by VovanPo",
    trivia: "-"
  },
  vsc: {
    name: "VSC",
    creator: "BoBoBoBoBoBoBo and Woom",
    verifier: "Yossarian",
    id: "60805571",
    password: "Free Copy",
    length: "16s",
    object: "24,638",
    version: "2.11",
    difficulty: "Insane(Challenge)",
    rating: "Unrated",
    youtube: "ewlMbTR-c_w",
    bgColor: "#483a05",
    song: "-Stalker- by Waterflame (ID 620959)",
    description: "Verified by Yossarian",
    trivia: "Former hardest challenge"
  },
  sakupendenouement: {
    name: "Sakupen Denouement",
    creator: "ad3usgmd(Nick24 and more)",
    verifier: "ad3usgmd",
    id: "133261698",
    password: "Free Copy",
    length: "52s",
    object: "73,225",
    version: "2.208",
    difficulty: "Harder",
    rating: "Unrated",
    youtube: "7Plzij-GNw4",
    bgColor: "#421c02",
    song: "Iron God: Sakupen Hell Yes RMX by mr-jazzman (ID 360804)",
    description: "-",
    trivia: "Current Top 1 of Denouement level"
  },
  slaughterhouse: {
    name: "Slaughterhouse",
    creator: "IcEDCave and more",
    verifier: "Doggie",
    id: "27690100",
    password: "147337",
    length: "1m 10s",
    object: "113,276",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "-",
    youtube: "kpcF1-QAHQc",
    bgColor: "#351112",
    song: "Tennobyte - Fly Away by Tennobyte (ID 945695), Lost by CRIM3S (NONG)",
    description: "THE GATES HAVE OPENED ONCE AGAIN.",
    trivia: "Former Top 1"
  },
  unnerfedzodiac: {
    name: "Unnerfed Zodiac",
    creator: "xander556 and more",
    verifier: "nebnoob",
    id: "54441585",
    password: "Free Copy",
    length: "3m 14s",
    object: "198,107",
    version: "2.11",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "3mvddPaNklg",
    bgColor: "#870c6f",
    song: "Creo - Sphere by CreoMusic (ID 739991)",
    description: "x_x",
    trivia: "Zodiac's unnerfed version"
  },
  kocmoc: {
    name: "KOCMOC",
    creator: "cherryteam",
    verifier: "Zoink",
    id: "87665224",
    password: "Free Copy",
    length: "1m 28s",
    object: "158,706",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "Epic",
    youtube: "2CxE-UWCIG4",
    bgColor: "#3e015c",
    song: "SLEEPING HUMMINGBIRD LONDON? Albee Remix ? by sawukalu164 (ID 1163222), Космос (∆XIUS LIИK Remix) by Sleeping Hummingbird (NONG)",
    description: "verified by Trick // verified by Zoink",
    trivia: "-"
  },
  chil: {
    name: "CHIL",
    creator: "McCoco",
    verifier: "McCoco",
    id: "114281093",
    password: "Free Copy",
    length: "1m 1s",
    object: "69,032",
    version: "2.207",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "DROMiCc2ZRM",
    bgColor: "#99003e",
    song: "Xy76 by Camellia (ID 10007183(library))",
    description: "Cold? Coolness? Chilly? Glacial? Nippy? Cool? Icy? Frosty? Chillax? Wintry? Freezing? Brisk? Chillness? Artic? Sharp? Chil without the L? Yeah",
    trivia: "Solo level(Layout, Design, Verify)"
  },
  element111rg: {
    name: "Element 111 Rg",
    creator: "Compendium(DarkX(Lost), Restoration Union)",
    verifier: "zoe",
    id: "61775814",
    password: "Free Copy",
    length: "1m 37s",
    object: "7,826",
    version: "2.11(1.6)",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "ZcdiTGuIJ1k",
    bgColor: "#222221",
    song: "Time Machine by Waterflame (ingame song)",
    description: "Theoretical version of Element 111 Rg by DarkX. Created and restored by Restoration Union.",
    trivia: "Old impossible level"
  },
  wockycircles: {
    name: "wocky circles",
    creator: "kywy",
    verifier: "ROZE",
    id: "100420930",
    password: "Free Copy",
    length: "1m 5s",
    object: "10,607",
    version: "2.205",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "yOx5Q3BkWIg",
    bgColor: "#020242",
    song: "Dr.Phonics - Firepower by DrPhonics (ID 490203)",
    description: "poland",
    trivia: "Sakupen Circles theme level"
  },
  sakupencircles: {
    name: "Sakupen Circles",
    creator: "Diamond(Nick24 and more)",
    verifier: "Diamond",
    id: "76962930",
    password: "Free Copy",
    length: "51s",
    object: "72,569",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "-",
    youtube: "ofG2mJi9kEA",
    bgColor: "#421c02",
    song: "Iron God: Sakupen Hell Yes RMX by mr-jazzman (ID 360804)",
    description: "By Nick24, DrCuber, korewa, Muffy450, Renn241, endevvor, Mzero, NineDice, GhostVandalf. Dedicated to Cursed",
    trivia: "Former Top 1, Old impossible level(decorated and a bit nerfed)"
  },
  exenslimit: {
    name: "Exens limit",
    creator: "Cursed(Nick24 and Zylenox)",
    verifier: "Cursed",
    id: "91675238",
    password: "Free Copy",
    length: "51s",
    object: "25,661",
    version: "2.11",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "KZksoQVGmKw",
    bgColor: "#421c02",
    song: "Iron God: Sakupen Hell Yes RMX by mr-jazzman (ID 360804)",
    description: "Secret way removed. Legitimately verified by me.",
    trivia: "Same as Unnerfed Sakupen circles but only nerfed wave spam"
  },
  wokecircles: {
    name: "WOKE circles",
    creator: "PPPixel(Nick24 and more)",
    verifier: "PPPixel",
    id: "88318424",
    password: "Free Copy",
    length: "50s",
    object: "27,466",
    version: "2.11",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "MKFeLVaBdoE",
    bgColor: "#944386",
    song: "Iron God: Sakupen Hell Yes RMX by mr-jazzman (ID 360804)",
    description: "-",
    trivia: "Same as Sakupen Circles' layout"
  },
  deimositshybrid: {
    name: "Deimos",
    creator: "ItsHybrid and more",
    verifier: "Doggie",
    id: "93091893",
    password: "Free Copy",
    length: "2m 57s",
    object: "157,646",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "b2yHaIk5zio",
    bgColor: "#351112",
    song: "[Deimos]* by Solkrieg (ID 830628)",
    description: "Megacollab made by 20+ people. Sequel to Phobos. Verified by Doggie in 43k attempts. GooD luck..",
    trivia: "-"
  },
  thelightningrod: {
    name: "The Lightning Rod",
    creator: "Lavatrex",
    verifier: "Lavatrex",
    id: "93917076",
    password: "Free Copy",
    length: "1m 37s",
    object: "44,710",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "nQDTi077O6M",
    bgColor: "#ff9036",
    song: "Beauty in Chaos by larrynachos (ID 935594)",
    description: "Solve the mystery of thunderstorms on a rainy day. 264 hours and 101 thousand attempts. My greatest project ever. Love you all! (bug @ 10% fixed 2/23/24).",
    trivia: "Solo level(Layout, Design, Verify)"
  },
  sightlesssandstorm: {
    name: "Sightless Sandstorm",
    creator: "Bradenbowl(crohn44)",
    verifier: "Bradenbowl",
    id: "68904235",
    password: "Free Copy",
    length: "1m 56s",
    object: "56,819",
    version: "2.11",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "0DAojkSfR-8",
    bgColor: "#a66826",
    song: "Creo - Outlaw by CreoMusic (ID 823812)",
    description: "I've made it through the Blizzard and the Sandstorm on instinct. #RateBlindBlizzard #RateSightlessSandstorm",
    trivia: "Invisible version of Sunset Sandstorm"
  },
  blindblizzard: {
    name: "Blind Blizzard",
    creator: "Bradenbowl(KrmaL)",
    verifier: "Bradenbowl",
    id: "65679976",
    password: "Free Copy",
    length: "1m 40s",
    object: "29,125",
    version: "2.11",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "veFJtgFFvNM",
    bgColor: "#252126",
    song: "Dimension by hyperdemented (ID 709578)",
    description: "What I created as a joke; ended up becoming a reality.",
    trivia: "Invisible version of Black Blizzard"
  },
  kosetsu: {
    name: "KOSETSU",
    creator: "fwwe and more",
    verifier: "Taiago",
    id: "109439644",
    password: "Free Copy",
    length: "1m 12s",
    object: "81,914",
    version: "2.206",
    difficulty: "Extreme Demon",
    rating: "Featured",
    youtube: "hZ8vFX8z_BU",
    bgColor: "#918dc2",
    song: "From Air by Lapse (ID 971534)",
    description: "Prepare for COLD",
    trivia: "cbf blocker deleted?"
  },
  trueinnards: {
    name: "True Innards",
    creator: "eandis(Kaito)",
    verifier: "eandis",
    id: "88216956",
    password: "Free Copy",
    length: "1m 25s",
    object: "66,489",
    version: "2.11",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "K77leSnLP0Y",
    bgColor: "#4f2723",
    song: "Dark Matter Suite (1f1n1ty + LOrbSheddy Remix) by 1f1n1ty (ID 693041)",
    description: "165~k attempts. (updated for ldm)",
    trivia: "Unnerfed version of INNARDS"
  },
  unnerfedyatagarasu: {
    name: "Unnerfed Yatagarasu",
    creator: "Compendium(TrusTa and more)",
    verifier: "Zoink",
    id: "28224824",
    password: "Free Copy",
    length: "2m 57s",
    object: "81,506",
    version: "2.11",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "qSdyb-Ft1tk",
    bgColor: "#400501",
    song: "Flawless Wings of Yatagarasu by Gls (ID 490479)",
    description: "As a tribute to TrusTa for verifying Yatagarasu, I have put together the unnerfed version before TrusTa's nerfs.",
    trivia: "Unnerfed version of Yatagarasu"
  },
  silentpoltergeist: {
    name: "Silent poltergeist",
    creator: "TheRealSailent and more",
    verifier: "Whizkid05",
    id: "13586257",
    password: "Copy Disabled",
    length: "1m 44s",
    object: "18,886",
    version: "2.0",
    difficulty: "Insane",
    rating: "Unrated",
    youtube: "XQ_TZc7cnPs",
    bgColor: "#222222",
    song: "NK - Poltergeist (OLD mix) by Rukkus (ID 587870)",
    description: "Collab with MaxPower GD and Nautilus2K. Fixed 2.1 version.",
    trivia: "Old impossible level(spam)"
  },
  firework: {
    name: "Firework",
    creator: "Trick(cherryteam)",
    verifier: "Trick",
    id: "75206202",
    password: "234000",
    length: "2m 7s",
    object: "165,198",
    version: "2.11",
    difficulty: "Extreme Demon",
    rating: "-",
    youtube: "QBe5x2o9v2w",
    bgColor: "#222222",
    song: "NK - Classical VIP by Rukkus (ID 502268)",
    description: "Here you die",
    trivia: "Lost Top 1(Slaughterhouse was hacked)"
  },
};
